# Generated by Django 4.1.4 on 2023-04-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_game_platform_rating_game_platforms_follow_comment"),
    ]

    operations = [
        migrations.DeleteModel(name="BookInstance",),
    ]
