# Generated by Django 4.1.4 on 2023-04-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_delete_bookinstance"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="author",),
        migrations.RemoveField(model_name="book", name="genre",),
        migrations.DeleteModel(name="Author",),
        migrations.DeleteModel(name="Book",),
    ]
