# Generated by Django 4.1.4 on 2023-04-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_game_likes_game_ratings_like"),
    ]

    operations = [
        migrations.RemoveField(model_name="game", name="likes",),
        migrations.RemoveField(model_name="game", name="ratings",),
        migrations.AddField(
            model_name="like", name="liked", field=models.BooleanField(default=False),
        ),
    ]
